module.exports ={
    HISTORY_ORDER:'HISTORY_ORDER',
    PRODUCT_LIST:'PRODUCT_LIST',
    CHECKOUT_INFORMATION:'CHECKOUT_INFORMATION',
    GO_TO_CHECKOUT:'GO_TO_CHECKOUT',
    CARD_NUMBER:'CARD_NUMBER',
    HISTORY_LIST:'HISTORY_LIST',
    DELIVERY_TIME:'DELIVERY_TIME',
}
